services:
  frontend:
    build:
      context: ./admin
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./admin:/app
      - /app/node_modules
    depends_on:
      - api

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: fullstackuser
      POSTGRES_PASSWORD: P@ssw0rd1
      POSTGRES_DB: fullstack
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fullstackuser -d fullstack"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  postgres-data:
